services:
  api:
    build: .
    environment:
      - APP_ENV=prod
    ports:
      - "8000:8000"
  frontend:
    image: node:20
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 5s
      timeout: 10s
      retries: 5
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    working_dir: /app
    environment:
      - CYPRESS_BASE_URL=http://frontend:5173
    entrypoint: ["npx", "cypress", "run"]
    depends_on:
      frontend:
        condition: service_healthy
