name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: bankcleanr-linux
            ext: ""
          - os: macos-latest
            artifact: bankcleanr-macos
            ext: ""
          - os: windows-latest
            artifact: bankcleanr-windows
            ext: ".exe"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Build executable
        run: poetry run bankcleanr build
      - name: Prepare artifact (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mv dist/bankcleanr dist/${{ matrix.artifact }}
          cd dist
          shasum -a 256 ${{ matrix.artifact }} > ${{ matrix.artifact }}.sha256
      - name: Prepare artifact (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Rename-Item dist/bankcleanr.exe "${{ matrix.artifact }}.exe"
          $hash = Get-FileHash "dist\${{ matrix.artifact }}.exe" -Algorithm SHA256
          "$($hash.Hash)  $($hash.Path | Split-Path -Leaf)" | Out-File -Encoding utf8 "dist\${{ matrix.artifact }}.sha256"
      - name: Upload release assets
        uses: softprops/action-gh-release@26994186c0ac3ef5cae75ac16aa32e8153525f77
        with:
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            dist/${{ matrix.artifact }}${{ matrix.ext }}
            dist/${{ matrix.artifact }}.sha256
